### PR TITLE
fix: honour the block max name length in BPK1

### LINKED ISSUE #8: Implement variable block max name length
Related: https://github.com/SwapdoodleRevival/libdoodle/blob/93156cb49c43c40944d48783090fe422fc3ada09/src/bpk1.rs#L46

Today I have discovered a file whose block max name length is 11 and not 7. This library uses 7 as a hardcoded value, so it fails to open this file.

Change de/serialization logic to reflect this change.

### PR DESCRIPTION
**Pull request by silver-volt4**
closes #8

### CODE REVIEW

File: src/bpk1.rs [hunk 1]
```diff
@@ -43,7 +43,6 @@ pub struct BPK1Block {
  - 8 bytes for the block name
 */
 const BPK1_BLOCK_HEADER_SIZE: usize = 0x4 + 0x4 + 0x4 + 0x8;
-const BPK1_BLOCK_NAME_MAX_LENGTH: u32 = 7;
```
Comment (CenTdemeern1) [inline src/bpk1.rs:46]: Note how the 8 bytes in `BPK1_BLOCK_HEADER_SIZE` are for the block name, making `BPK1_BLOCK_HEADER_SIZE` inaccurate

File: src/bpk1.rs [hunk 2]
```diff
@@ -169,7 +175,7 @@ where
             writer.write_u32_le(0)?; // will be offset
             writer.write_u32_le(block.data.len() as u32)?;
             writer.write_u32_le(calc_bpk1_checksum(&block.data))?;
-            writer.write_all(&cstring_to_bpk1_bytes(&block.name))?;
+            writer.write_all(&cstring_to_bpk1_bytes(&block.name, max_name_len + 1))?;
```
Comment (CenTdemeern1) [inline src/bpk1.rs:167]: This feels like an off-by-one error

**Review by CenTdemeern1 — CHANGES_REQUESTED** [review]

File: src/bpk1.rs (hunk 1 above)
Comment (silver-volt4) [reply src/bpk1.rs:46]: Shoot, I forgot about that.
The extractor worked fine though? Weird.

edit: constant only used in the writer (not reader)

File: src/bpk1.rs (hunk 2 above)
Comment (silver-volt4) [reply src/bpk1.rs:167]: https://github.com/SwapdoodleRevival/libdoodle/pull/9/changes/BASE..1fb3227a0013a296e011810082828f14b52021ba#diff-e18d296f5a372f7f91687d3bf600a2ebb6f7a1c8e8dfcabdb90118809cb6122cR158

```
core::ffi::c_str::CStr

pub const fn count_bytes(&self) -> usize

Returns the length of self. Like C's strlen, this does not include the nul terminator.
```

> this does not include the nul terminator

the +1 is for the final nullterm

Comment (silver-volt4) [reply src/bpk1.rs:167]: Image

notice how the file reports a max length of 11 but the name is 12 bytes

unless this is some weird alignment shite?

Comment (CenTdemeern1) [reply src/bpk1.rs:167]: Didn't you already add 1 for the null terminator here? https://github.com/SwapdoodleRevival/libdoodle/blob/e03469ae96529f73a06957577a1d7fac11a6b864/src/bpk1.rs#L93

File: src/bpk1.rs [hunk 3]
```diff
@@ -178,6 +167,9 @@ where
             writer.write_all(&cstring_to_bpk1_bytes(&block.name, max_name_len + 1))?;
         }
 
+        // u32 + u32 + u32 + max_name_len+1 (see above)
+        let block_header_total_size: usize = 0x4 + 0x4 + 0x4 + max_name_len + 1;
```
Comment (CenTdemeern1) [inline src/bpk1.rs:171]: Ditto, off-by-one

**Review by CenTdemeern1 — CHANGES_REQUESTED** [review]

File: src/bpk1.rs (hunk 2 above)
Comment (silver-volt4) [reply src/bpk1.rs:167]: It's a completely different function, this is in the read function 
Notice how the variables even have different names

Comment (CenTdemeern1) [reply src/bpk1.rs:167]: Oops, I didn't realize these were different functions

**Review by CenTdemeern1 — APPROVED** [review]

**Comment by CenTdemeern1** [comment]
~~I'll assume that you tested the code so I don't have to do it myself~~
